// Purpose of this file is to generate README.md

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  Project,
  SyntaxKind,
  type ArrowFunction,
  type FunctionExpression,
  type Block,
} from "ts-morph";
import { md } from "./md.ts";
import { getOperations, getOrDownloadSpec } from "../dump-spec-info.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEST_FILE = resolve(__dirname, "../../tests/docs.test.ts");
const README_FILE = resolve(__dirname, "../../README.md");

const README_START = md`
<!-- This file is generated by \`pnpm run docs\`, do not edit manually. -->

# ngsi-ld-sdk

This wrapper hopes to be a Node package for calling NGSI-LD APIs, right now test
cases are ran against Orion-LD and Stellio.

Code was generated with Orval from [NGSI-LD OpenAPI
spec](https://forge.etsi.org/rep/cim/ngsi-ld-openapi/-/raw/v1.8.1/openapi-3.0.3/ngsi-ld-api.yaml),
however generation result was too verbose so I've continued to maintain it without Orval.
`;

const README_END = md`
## Notes

This wrapper intentionally sets the Content-Type and Accept headers to \`application/ld+json\` for all requests. One exception: \`queryBatch\` and \`temporalQueryBatch\` are still using \`application/json\`, reason being that Stellio didn't support \`@context\` proeprty in query batch and temporal query batch, but Orion-LD did. Thus the SDK wrapper sets the Content-Type and Accept headers to \`application/json\` for those two requests.
`;

/** Strip 4 spaces of indentation from each non-empty line. */
function dedent4(text: string): string {
  return text
    .split("\n")
    .map((l) => (l.trim() === "" ? "" : l.startsWith("    ") ? l.slice(4) : l))
    .join("\n");
}

/**
 * Extracts the body statements from a function-like node (arrow function or function expression).
 * Returns the source text of the body, dedented.
 */
function extractBodyText(fn: ArrowFunction | FunctionExpression): string {
  const body = fn.getBody();
  if (!body) return "";

  if (body.isKind(SyntaxKind.Block)) {
    const block = body as Block;
    const raw = block
      .getStatements()
      .map((s) => s.getText())
      .join("\n");
    return dedent4(raw);
  }

  // Concise arrow body: `() => expr`
  return body.getText();
}

async function getDocTestExamples(): Promise<string> {
  const project = new Project();
  const sourceFile = project.addSourceFileAtPath(TEST_FILE);

  const examples: string[] = [];

  for (const callExpr of sourceFile.getDescendantsOfKind(
    SyntaxKind.CallExpression,
  )) {
    const expr = callExpr.getExpression();
    // Match `it(...)` calls (skip `it.skip`, `it.only`, and describe blocks)
    if (expr.getText() !== "it") continue;

    const args = callExpr.getArguments();
    // it("description", callback)
    if (args.length < 2) continue;

    // First arg: the test description string
    const rawDesc = args[0].getText();
    const description = rawDesc.replace(/^["']|["']$/g, "");
    // Derive a heading from the description (e.g. "createEntity example should work" → "createEntity")
    const heading = description
      .replace(/\s+example.*$/, "")
      .replace(/\s+should.*$/, "");

    // Second arg: the callback (arrow function or function expression)
    const callback = args[1];
    let bodyText: string;

    if (callback.isKind(SyntaxKind.ArrowFunction)) {
      bodyText = extractBodyText(callback as ArrowFunction);
    } else if (callback.isKind(SyntaxKind.FunctionExpression)) {
      bodyText = extractBodyText(callback as FunctionExpression);
    } else {
      continue;
    }

    const trimmed = bodyText.trim();
    if (trimmed) {
      examples.push(`### ${heading}\n\n\`\`\`typescript\n${trimmed}\n\`\`\``);
    }
  }

  return examples.join("\n\n");
}

async function generateOperationsTable(): Promise<string> {
  const spec = await getOrDownloadSpec();
  const specOperations = getOperations(spec);

  // Build a lookup from spec operationId -> { method, path }
  const specByOperationId = new Map<string, { method: string; path: string }>();
  for (const op of specOperations) {
    specByOperationId.set(op.operationId, { method: op.method, path: op.path });
  }

  // Use ts-morph to extract all exported const names from operations.ts
  const project = new Project();
  const operationsFile = project.addSourceFileAtPath(
    resolve(__dirname, "../../src/api/operations.ts"),
  );

  const sdkExports = operationsFile
    .getVariableDeclarations()
    .filter((v) => v.isExported())
    .map((v) => v.getName());

  // Build table rows: SDK name | METHOD | spec path (or "—" if not in spec)
  const rows: string[] = [
    "| SDK function | Method | Spec path |",
    "| --- | --- | --- |",
  ];

  for (const name of sdkExports) {
    const spec = specByOperationId.get(name);
    rows.push(
      `| \`${name}\` | \`${spec?.method ?? "—"}\` | \`${spec?.path ?? "—"}\` |`,
    );
  }

  return rows.join("\n");
}

export async function generateReadme() {
  // Generate README.md content
  let readme = README_START;
  readme += "\n## Usage\n\n";
  readme += await getDocTestExamples();
  readme += "\n\n## Operations\n\n";
  readme += await generateOperationsTable();
  readme += "\n\n";
  readme += README_END;
  return readme;
}

if (import.meta.main) {
  const readme = await generateReadme();
  writeFileSync(README_FILE, readme + "\n");
  console.log(`README.md written to ${README_FILE}`);
}
